# Site settings
name: Aryan Yadav
title: Aryan Yadav
description: A student and software developer focused on building meaningful applications and experiences
url: https://starwiz-7.github.io/
baseurl: ''
email: aryan2019@iiitkottayam.ac.in
cover: https://starwiz-7.github.io/img/og.png
logo: https://starwiz-7.github.io/img/emojis/technologist.png
resume: https://starwiz-7.github.io/resume.pdf
social:
  - title: email
    url: mailto:aryan2019@iiitkottayam.ac.in
  - title: twitter
    url: https://twitter.com/7aryany
  - title: instagram
    url: https://instagram.com/aryann__7
  - title: github
    url: https://github.com/starwiz-7
  - title: linkedin
    url: https://www.linkedin.com/in/yadav-aryan

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
